-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUsiEEKRSetlsAssm
y/XUXQEexBZ3F2XM+UNVps826pmgCgYIKoZIzj0DAQehRANCAATnxaqWM/CLla8y
yCwEEiSgM4BBIII4JdYykNdc189NGEhvww0tiW1493azQ1GhI3f01nxJSmsjexK/
/JkGlaDc
-----END PRIVATE KEY-----